# Generated by Django 3.2.6 on 2021-09-29 01:06

import django.contrib.postgres.indexes
from django.db import migrations, models

import saleor.core.utils.json_serializer


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0147_auto_20210817_1015"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariantchannellisting",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productvariantchannellisting",
            name="private_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="productvariantchannellisting",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["private_metadata"], name="variantchannels_p_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariantchannellisting",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="variantchannels_meta_idx"
            ),
        ),
    ]
