# Generated by Django 3.2.6 on 2021-10-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0036_merge_20210824_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_preorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkout',
            name='requested_shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
