# Generated by Django 3.2.6 on 2021-10-15 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0148_auto_20210929_0806"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductClassRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_class_qty",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "product_class_value",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "product_class_recommendation",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Initial product class recommendation"),
                            (
                                "SUBMITTED",
                                "Product class submitted, waiting for approval",
                            ),
                            ("APPROVED", "Product class approved"),
                        ],
                        default="DRAFT",
                        max_length=128,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_approved_product_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_created_product_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_class_recommendations",
                        to="product.productvariantchannellisting",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_updated_product_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("manage_product_class", "Manage product class recommendation."),
                    ("approve_product_class", "Approve product class recommendation."),
                ),
            },
        ),
    ]
