# Generated by Django 3.2.6 on 2021-09-29 01:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product_class", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productclassrecommendation",
            options={
                "permissions": (
                    ("manage_product_class", "Manage product class recommendation."),
                )
            },
        ),
    ]
