# Generated by Django 3.2.6 on 2021-09-29 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('product_class', '0002_alter_productclassrecommendation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productclassrecommendation',
            options={'permissions': (
            ('manage_product_class', 'Manage product class recommendation.'),
            ('approve_product_class', 'Approve product class recommendation.'))},
        ),
    ]
