# Generated by Django 3.2.6 on 2021-10-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SaleorAI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scgh_mch3_code",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "scgh_mch3_desc",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "scgh_mch2_code",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "scgh_mch2_desc",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "scgh_mch1_code",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "scgh_mch1_desc",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("brand", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "article_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "article_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("item_flag", models.CharField(blank=True, max_length=50, null=True)),
                ("item_status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "scgh_dc_item_flag",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "scgh_dc_stock",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "scgh_show_no_stock_flag",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "scgh_product_class",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("scgh_vmi_flag", models.BooleanField(default=False)),
                ("scgh_showroom_flag", models.BooleanField(default=False)),
                ("scgh_market_flag", models.BooleanField(default=False)),
                ("scgh_shop_flag", models.BooleanField(default=False)),
                ("sales_uom", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "sales_price",
                    models.DecimalField(decimal_places=12, default=0, max_digits=21),
                ),
                (
                    "purchase_uom",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=12, default=0, max_digits=21),
                ),
                (
                    "purchase_group",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("moq", models.CharField(blank=True, max_length=10, null=True)),
                ("vendor_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "vendor_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("comp_code", models.CharField(blank=True, max_length=50, null=True)),
                ("comp_desc", models.CharField(blank=True, max_length=256, null=True)),
                ("dc_rdc_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "dc_rdc_desc",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "franchise_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "franchise_desc",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("actual_sales_value", models.IntegerField(default=0)),
                ("actual_sales_qty", models.IntegerField(default=0)),
                (
                    "forecast_value",
                    models.DecimalField(decimal_places=12, default=0, max_digits=21),
                ),
                ("forecast_qty", models.IntegerField(default=0)),
                ("safety_stock_qty", models.IntegerField(default=0)),
                ("min_qty", models.IntegerField(default=0)),
                ("max_qty", models.IntegerField(default=0)),
                (
                    "product_class_qty",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "product_class_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "product_class_default",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("start_of_week", models.DateField(blank=True, null=True)),
                ("start_of_month", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
