# Generated by Django 3.2.6 on 2021-09-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0116_merge_20210824_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='request_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
